License file checksum for trusted-firmware-a 2.6
Address a new QA error in kirkstone.

 ERROR: trusted-firmware-a-2.6-r0 do_populate_lic: QA Issue:
 trusted-firmware-a: Recipe file fetches files and does not have
 license file information (LIC_FILES_CHKSUM) [license-checksum]
 ERROR: trusted-firmware-a-2.6-r0 do_populate_lic: Fatal QA errors
 were found, failing task.
 ERROR: Logfile of failure stored in: .../log.do_populate_lic.10593
 ERROR: Task (.../trusted-firmware-a_2.6.bb:do_populate_lic) failed
 with exit code '1'